export const MODULES = [
  {
    id: "chat",
    titleKey: "modules.chat.title",
    descriptionKey: "modules.chat.description",
    icon: "chatbubble-outline",
    gradientColors: ["#4F8EF7", "#235390"], // Chat modülü renkleri
    route: "Chat",
    enabled: true,
    showQuickArea: false,
    tokenCost: 0,
    category: "tools",
  },
  {
    id: "math",
    titleKey: "modules.math.title",
    descriptionKey: "modules.math.description",
    icon: "calculator-outline",
    gradientColors: ["#4F8EF7", "#235390"], // Matematik modülü renkleri
    route: "Math",
    enabled: true,
    showQuickArea: true,
    tokenCost: 2,
    category: "education",
  },
  // {
  //   id: "voiceNote",
  //   titleKey: "modules.voiceNote.title",
  //   descriptionKey: "modules.voiceNote.description",
  //   icon: "mic-outline",
  //   gradientColors: ["#5C7AE7", "#3C5DCB"],
  //   route: "VoiceNote",
  //   enabled: true,
  //   showQuickArea: true,
  //   tokenCost: 0,
  //   category: "tools",
  // },
  // {
  //   id: "pdfEditor",
  //   titleKey: "modules.pdfEditor.title",
  //   descriptionKey: "modules.pdfEditor.description",
  //   icon: "document-text-outline",
  //   gradientColors: ["#7B8FA8", "#4B5A6B"],
  //   route: "PDFEditor",
  //   enabled: true,
  //   showQuickArea: true,
  //   tokenCost: 0,
  //   category: "productivity",
  // },
  // {
  //   id: "ocr",
  //   titleKey: "modules.ocr.title",
  //   descriptionKey: "modules.ocr.description",
  //   icon: "scan-outline",
  //   gradientColors: ["#F59E42", "#F47C1A"],
  //   route: "OCR",
  //   enabled: true,
  //   showQuickArea: true,
  //   tokenCost: 0,
  //   category: "tools",
  // },
  {
    id: "quiz",
    titleKey: "modules.quiz.title",
    descriptionKey: "modules.quiz.description",
    icon: "help-buoy-outline",
    gradientColors: ["#F472B6", "#C026D3"], // Quiz modülü renkleri
    route: "Quiz",
    enabled: true,
    showQuickArea: true,
    tokenCost: 3,
    category: "education",
  },
  {
    id: "calculator",
    titleKey: "modules.calculator.title",
    descriptionKey: "modules.calculator.description",
    icon: "calculator",
    gradientColors: ["#10B981", "#059669"], // Hesap makinesi yeşil renkleri
    route: "Calculator",
    enabled: true,
    showQuickArea: true,
    tokenCost: 0,
    category: "tools",
  },
];
